### ISSUE TITLE
make default matplotlib backend TkAgg instead of WebAgg

### ISSUE THREAD

**Issue by sbailey** [desihub/desiconda#12]
For some reason, our default matplotlib backend is WebAgg instead of something reasonable like TkAgg:
```
[cori02 ~] grep ^backend /global/common/software/desi/cori/desiconda/20170920-1.2.0-spec/conda/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc
backend      : WebAgg
```
The spectro pipeline resets the backend anyway, but WebAgg is a bad backend for interactive work and we should have a better default if we can figure out the recipe for doing that automatically for new installs.

In the meantime, users can override this with their `~/.config/matplotlib/matplotlibrc` file, though ideally we shouldn't rely upon a recipe that requires every user to do something custom to work.

**Comment by tskisner** [comment]
Fixed in 5876cbd83a08935953a0ad9e600ddaba2055d359, default backend hardcoded to TkAgg.
