### ISSUE TITLE
pre-build matplotlib font cache and astropy config stuff

### ISSUE THREAD

**Issue by sbailey** [desihub/desiconda#13]
In desihub/desispec#494, @tskisner said:
> For docker images, I do pre-build the font cache (and also the astropy config stuff). I could easily do that for regular desiconda installs too.

Yes, please do.

**Comment by tskisner** [comment]
Should be fixed by 05dba302f56657a810bb55cac2d7eb97d0594bf5.  Note that astropy config is a per-user thing, so it only helps when running in a docker container where we can create a fake $HOME directory and force astropy to create config files inside there.
