### ISSUE TITLE
user envs from desiconda 20180130-1.2.4-spec are broken

### ISSUE THREAD

**Issue by sbailey** [desihub/desiconda#16]
Turning this email into a ticket for tracking:
I'm trying to create a user conda environment based on desiconda 20180130-1.2.4-spec to install some non-DESI packages and am getting Permission denied errors.  e.g.

```
module use /global/common/software/desi/cori/desiconda/20180130-1.2.4-spec/modulefiles/
module load desiconda
conda create -n test
source activate test
conda install pandas
...
PermissionError(13, 'Permission denied')
```

The same works if I start with NERSC python/3.6-anaconda-4.4 instead.  How can we fix this so that users can start with desiconda to create their own environments to install additional packages?

Associating with desihub project 18.3 in the hopes that this can be fixed in-place before the final release in March 2018.

**Comment by tskisner** [comment]
I got a different error when trying to clone the root environment, due to some stale cache objects.  I just did conda clean --all as the desi user.  Will report back shortly

**Comment by sbailey** [comment]
Another data point: this also fails for me with `/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro`, which I thought had previously worked for user environments.

**Comment by tskisner** [comment]
If I follow our "usual procedure":
```
$>  conda create -n test --copy --file ${DESICONDA}/pkg_list.txt
```
Then conda crashes with "an expected error".  It looks like it gets a permission error since it is trying to use the cache directory in the conda root environment (which of course it does not have write access to).  I don't understand why its trying to right to that cache directory now when it did not previously do that.  Will try to see if I can get it to use a per-user cache directory.

**Comment by tskisner** [comment]
OK, I got it to work by doing:
```
$>  export CONDA_PKGS_DIRS=$HOME/.conda/pkgs
$>  conda create -n test --copy --file ${DESICONDA}/pkg_list.txt
```
Based on the info here:
https://github.com/conda/conda/issues/3885

**Comment by tskisner** [comment]
NOTE:  in your original post in this issue, you did not clone the desiconda package list.  That may or may not work, but it definitely voids the warranty :-)   All the compiled / hybrid packages built with desiconda are still in your environment, so your custom environment should really start with the original desiconda package list, and then add extra packages.

**Comment by tskisner** [comment]
@sbailey, we can close this as soon as you verify that it works for you...

**Comment by sbailey** [comment]
I confirm that this works and I updated our wiki documentation.  Given this `$CONDA_PKGS_DIRS` solution, I'm surprised that it works for the NERSC-provided conda installs without setting that.  Closing.
