### ISSUE TITLE
Weird missing symbol when compiling a python extension

### ISSUE THREAD

**Issue by dstndstn** [desihub/desiconda#20]
Hi,

Not sure if this is desiconda related, but...

I'm investigating a bug in fitsio and I wanted to check whether the master version of fitsio still shows the problem.  I checked out that code, ran "python3 setup.py install --home=$(pwd)" and set my PYTHONPATH to pick up that directory.  (python3 is /global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/bin/python3), and it compiles cleanly, but then:

cd && python -c "import fitsio"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/global/homes/d/dstn/fitsio/lib/python/fitsio/__init__.py", line 9, in <module>
    from . import fitslib
  File "/global/homes/d/dstn/fitsio/lib/python/fitsio/fitslib.py", line 29, in <module>
    from . import _fitsio_wrap
ImportError: /global/homes/d/dstn/fitsio/lib/python/fitsio/_fitsio_wrap.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __intel_cpu_feature_indicator

Now,

> ldd /global/homes/d/dstn/fitsio/lib/python/fitsio/_fitsio_wrap.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007ffc837ce000)
        libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00002b6308d2b000)
        libm.so.6 => /lib64/libm.so.6 (0x00002b6308f9b000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b6309298000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b63094b5000)
        libidn.so.11 => /usr/lib64/libidn.so.11 (0x00002b6309856000)
        libssh2.so.1 => /usr/lib64/libssh2.so.1 (0x00002b6309a8a000)
        libssl.so.1.0.0 => /global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/libssl.so.1.0.0 (0x00002b6309cb6000)
        libcrypto.so.1.0.0 => /global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/libcrypto.so.1.0.0 (0x00002b6309f2c000)
        libgssapi_krb5.so.2 => /global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/libgssapi_krb5.so.2 (0x00002b630a36c000)
        liblber-2.4.so.2 => /usr/lib64/liblber-2.4.so.2 (0x00002b630a5b5000)
        libldap-2.4.so.2 => /usr/lib64/libldap-2.4.so.2 (0x00002b630a7c4000)
        libz.so.1 => /global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/libz.so.1 (0x00002b630aa10000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b6308728000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002b630ac27000)
        libkrb5.so.3 => /global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/./libkrb5.so.3 (0x00002b630ae2b000)
        libk5crypto.so.3 => /global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/./libk5crypto.so.3 (0x00002b630b0ff000)
        libcom_err.so.3 => /global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/./libcom_err.so.3 (0x00002b630b31b000)
        libkrb5support.so.0 => /global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/./libkrb5support.so.0 (0x00002b630b51e000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00002b630b729000)
        libsasl2.so.3 => /usr/lib64/libsasl2.so.3 (0x00002b630b940000)

I think this symbol is supposed to be in some icc library??  It looks like the fitsio module is getting compiled with gcc.

**Comment by tskisner** [comment]
Hmmm.  At NERSC, we build cfitsio (and all compiled packages) with the Intel compiler.  Then we pip-install fitsio like:
```
pip install --no-binary :all: https://github.com/esheldon/fitsio/archive/v0.9.12rc1.zip
```
Which compiles the extension using our cfitsio (or that's what I assumed).  It is true that this will use gcc for the build, since that is what python distutils is using.  However, there have been no issues until now with fitsio linking.

Perhaps the dist tarballs of fitsio actually bundle cfitsio, but the git master checkout does not?  That would explain why building from the zip file works (if it builds its own cfitsio internally).

**Comment by dstndstn** [comment]
Thanks for the tip on how you build fitsio.  I just tried it with fitsio master,

> pip install --user --upgrade --no-deps --no-binary :all: git+https://github.com/esheldon/fitsio/
Collecting git+https://github.com/esheldon/fitsio/
  Cloning https://github.com/esheldon/fitsio/ to /tmp/pip-4a6371z5-build
Installing collected packages: fitsio
  Running setup.py install for fitsio ... done
Successfully installed fitsio-1.0.0rc1
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

and I get the same error:

> python3 -c "import fitsio"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/global/homes/d/dstn/.local/lib/python3.6/site-packages/fitsio/__init__.py", line 9, in <module>
    from . import fitslib
  File "/global/homes/d/dstn/.local/lib/python3.6/site-packages/fitsio/fitslib.py", line 29, in <module>
    from . import _fitsio_wrap
ImportError: /global/homes/d/dstn/.local/lib/python3.6/site-packages/fitsio/_fitsio_wrap.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __intel_cpu_feature_indicator

**Comment by tskisner** [comment]
I'm confused why the output of "ldd" on your fitsio wrapper library has so many listings.  I just checked the last couple desiconda installs and I get something like:
```
$ module use /global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/modulefiles
$ module load desiconda
$ ldd /global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/_fitsio_wrap.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007ffc03efb000)
        libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00002b54ca24d000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b54ca45c000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b54ca679000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b54c9c72000)
```
This seems to indicate that fitsio is statically linking to cfitsio and most other things.  Did something change in the way fitsio finds or links to cfitsio?

**Comment by dstndstn** [comment]
Yeah, it does look like it's creating its own libcfitsio.a...

gcc -pthread -shared -B
/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/compiler_compat
-L/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib
-Wl,-rpath=/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib
-Wl,--no-as-needed -Wl,--sysroot=/
build/temp.linux-x86_64-3.6/fitsio/fitsio_pywrap.o
build/temp.linux-x86_64-3.6/cfitsio3430patch/libcfitsio.a -lbz2 -lcurl -lm
-o build/lib.linux-x86_64-3.6/fitsio/_
fitsio_wrap.cpython-36m-x86_64-linux-gnu.so

**Comment by weaverba137** [comment]
@dstndstn, this ticket applies to a very old version of desiconda. Is it OK to close this?

**Comment by dstndstn** [comment]
Yes, fine!
