### ISSUE TITLE
cori-gcc-py27 for CONFIG

### ISSUE THREAD

**Issue by DriftingPig** [desihub/desiconda#22]
Hi,
I tried to install desiconda on cori, and the command:
`CONFIG=cori-gcc-py27 PREFIX=$SCRATCH/software make imaging`
gives me error:
`make: *** No rule to make target 'conf/cori-gcc-py27', needed by 'imaging'.  Stop.`

should there be some file in the conf folder called cori-gcc-py27?

**Comment by tskisner** [comment]
Yes, that is what the CONFIG variable describes (the name of the file in the conf directory.  FYI we are no longer using python2.7 for our spectro pipeline installs or our imaging installs.  It may still work, but...

You can copy the cori-gcc files (cori-gcc, cori-gcc.module, cori-gcc.sh) to the name you propose, and then edit the cori-gcc-py27 file to set PYVERSION to 2.7 and change Miniconda3 --> Miniconda2.

Actually, I notice that the cori-gcc files were not updated to match the dependencies loaded.  I'll do that shortly, so wait until I push that before copying them.

**Comment by tskisner** [comment]
Actually, since I'm editing these files right now anyway, I'll just create the py27 ones.

**Comment by DriftingPig** [comment]
Thank you!
