### ISSUE TITLE
Update to new version of pip

### ISSUE THREAD

**Issue by dkirkby** [desihub/desiconda#26]
The desiconda env includes `pip` (good!) but an old version:
```
% pip list
...
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
This issue is to update to a newer version.  I don't know of any missing new features that we need, but at least it would silence this warning.

Note that version 10.0.1 is not as old as it sounds (released Apr 2018) because pip has an unusual [recent version history](https://pip.pypa.io/en/stable/news/).

**Comment by weaverba137** [comment]
@dkirkby, I don't think it is worth keeping this ticket open.

**Comment by weaverba137** [comment]
It's been a year with no objections, so I'm closing this.
