### ISSUE TITLE
qdo crash with most recent software stack 20190311-1.2.7-img

### ISSUE THREAD

**Issue by moustakas** [desihub/desiconda#28]
```
[snip]
Starting qdo job on nid00535 at Tue Mar 12 06:37:58 PDT 2019
QDO environment variables:
QDO_DIR=/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/aux/lib/python3.6/site-packages/qdo-0.8.dev1-py3.6.egg
QDO_DB_USER=desirun_admin
QDO_DB_HOST=nerscdb03.nersc.gov
QDO_SCRIPT=./dr8-runbrick-decam.sh
QDO_BATCH_PROFILE=cori
QDO_BACKEDUP_PATH=/global/project/projectdirs/cosmo/work/legacysurvey/dr8b/runbrick-decam/code/legacyzpts/bin:/global/project/project
dirs/cosmo/work/legacysurvey/dr8b/runbrick-decam/code/legacypipe/bin:/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/a
ux/bin:/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/conda/bin:/global/common/sw/cray/cnl6/haswell/git/2.15.1/gcc/4.
8/vfffcvo/bin:/opt/gcc/7.3.0/bin:/usr/common/software/bin:/usr/common/mss/bin:/usr/common/nsg/bin:/usr/common/software/bin:/usr/commo
n/mss/bin:/usr/common/nsg/bin:/opt/cray/pe/mpt/7.7.3/gni/bin:/opt/cray/rca/2.2.18-6.0.7.0_33.3__g2aa4f39.ari/bin:/opt/cray/alps/6.6.4
3-6.0.7.0_26.4__ga796da3.ari/sbin:/opt/cray/job/2.2.3-6.0.7.0_44.1__g6c4e934.ari/bin:/opt/cray/pe/craype/2.5.15/bin:/opt/intel/compil
ers_and_libraries_2018.1.163/linux/bin/intel64:/opt/ovis/bin:/opt/ovis/sbin:/usr/syscom/nsg/sbin:/usr/syscom/nsg/bin:/opt/cray/pe/mod
ules/3.2.10.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/cray/pe/bin:/global/cs
cratch1/sd/desiproc/code/qdo/bin:/global/cscratch1/sd/desiproc/code/qdo/bin:/global/cscratch1/sd/desiproc/code/qdo/bin:/global/cscrat
ch1/sd/desiproc/code/qdo/bin
QDO_NAME=dr8b-test-hsc-ngc-decam
QDO_BACKEND=postgres
QDO_DB_NAME=desirun
QDO_DB_PASS=32j2j253ss
QDO_WORKERS_PER_JOB=256
QDO_OPTS=--timeout 60 --jitter 64.00
QDO_MPIRUN=srun -n 256 --ntasks-per-node=4 --cpus-per-task=8 --exclusive --cpu_bind=cores --threads-per-core=1
srun -n 256 --ntasks-per-node=4 --cpus-per-task=8 --exclusive --cpu_bind=cores --threads-per-core=1 /global/common/software/desi/cori
/desiconda/20190311-1.2.7-img/aux/lib/python3.6/site-packages/qdo-0.8.dev1-py3.6.egg/bin/qdo do dr8b-test-hsc-ngc-decam --timeout 60 
--jitter 64.00 --script ./dr8-runbrick-decam.sh
srun: fatal: Can not execute /global/common/software/desi/cori/desiconda/20190311-1.2.7-img/aux/lib/python3.6/site-packages/qdo-0.8.d
ev1-py3.6.egg/bin/qdo
/var/spool/slurmd/job19656433/slurm_script: line 35: 16032 Aborted                 $QDO_MPIRUN $QDO_DIR/bin/qdo do $QDO_NAME $QDO_OPT
S --script "$QDO_SCRIPT"
[snip]
```

**Comment by tskisner** [comment]
QDO was installed with:
```
python setup.py install --prefix=<blah>
```
Does that not work for some reason?  Usually if a setup.py exists I expect it to just work for installation...

**Comment by moustakas** [comment]
I don't know, I'm a "add local check-out to my PYTHONPATH" kinda guy.  Is there any way to run the test suite?  (Sorry, I'm just not sure how to get to the `test` directory.)
```
cd test
python -m unittest discover
```
https://bitbucket.org/berkeleylab/qdo

Also, just to confirm that you pulled down the `master` branch?  I'm not sure when the last release was, but Dustin and others have committed stuff since then (although I'm not sure how mission-critical those changes are).

**Comment by tskisner** [comment]
Ok, I saw the setup.py and blindly assumed that it followed standard python packaging conventions.  I'll go look deeper to see if there are some manual steps needed for installation.

**Comment by tskisner** [comment]
The install of the qdo egg and script entry points look fine.  If I load the desiconda version above, I can do (for example):
```
qdo --help
```
without any import error.  Does that command work for you?  Is it possible that you still have an alternate qdo git checkout in your PATH / PYTHONPATH?

**Comment by moustakas** [comment]
You are absolutely right.  I didn't realize that a bunch of `qdo` setup commands had been put in the `desiproc` `.bashrc.ext` file.

I'll re-test and if there are no issues I'll close this issue without comment.  Thank you!

**Comment by moustakas** [comment]
I'm still getting the same crash.  `which qdo` yields `/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/aux/bin/qdo` but when I launch my slurm script, qdo looks for the executables in `/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/aux/lib/python3.6/site-packages/qdo-0.8.dev1-py3.6.egg/bin/qdo` which is obviously wrong.

**Comment by moustakas** [comment]
Let me try defining explicitly defining `QDO_DIR` after loading the desiconda stack.

**Comment by moustakas** [comment]
Unfortunately, explicitly doing
`export QDO_DIR=/global/common/software/desi/$NERSC_HOST/desiconda/$desiconda_version/aux/bin/qdo`
after desiconda is loaded breaks the command-line `qdo`.
```
desiproc@cori06:/global/u2/d/desiproc/dr8b/runbrick-decam> which qdo
/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/aux/bin/qdo
desiproc@cori06:/global/u2/d/desiproc/dr8b/runbrick-decam> qdo --help
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/aux/bin/qdo", line 4, in <module>
    __import__('pkg_resources').run_script('qdo==0.8.dev1', 'qdo')
  File "/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/aux/lib/python3.6/site-packages/qdo-0.8.dev1-py3.6.egg/EGG-INFO/scripts/qdo", line 4, in <module>
    import qdo.console
  File "/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/aux/lib/python3.6/site-packages/qdo-0.8.dev1-py3.6.egg/qdo/__init__.py", line 35, in <module>
    from .core import __version__
  File "/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/aux/lib/python3.6/site-packages/qdo-0.8.dev1-py3.6.egg/qdo/core.py", line 1278, in <module>
    _parse_configuration()
  File "/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/aux/lib/python3.6/site-packages/qdo-0.8.dev1-py3.6.egg/qdo/core.py", line 1276, in _parse_configuration
    shutil.copyfile(orig_qdorc, qdorc_route)
  File "/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/conda/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
NotADirectoryError: [Errno 20] Not a directory: '/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/aux/bin/qdo/qdorc'
```

Maybe the contents of 
`/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/aux/bin`
should have been---but weren't---installed / copied to `/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/aux/lib/python3.6/site-packages/qdo-0.8.dev1-py3.6.egg/bin/qdo` ?

**Comment by moustakas** [comment]
Just noting that this is still an issue, with the work-around being to use a local installation of `qdo`.

**Comment by tskisner** [comment]
I don't think this is an install issue.  The python modules load fine.  This seems like an environment issue.  If QDO requires extensive customization to work, then perhaps it is not really something that makes sense to have in desiconda...

**Comment by moustakas** [comment]
Thanks, @tskisner, agreed.  Perhaps @sbailey has some insight, otherwise I'll go with what I have for now.

**Comment by sbailey** [comment]
With apologies for the less-than-production-level-code, some notes:
* I agree with not including qdo in the desiconda releases.  Even if setup.py etc. was working perfectly, Dustin contributes qdo changes a bit more frequently than desiconda rebuilds, so it is useful to keep them separated.
* It could be useful to install qdo as an optional module though
* If you have a viable workaround, go for it.  I don't know how to uninstall qdo from an already existing desiconda, but holler loudly if we need to install a new version of desiconda.
* With Cori out today, I can't test this particular case right now.

All of that being said, I thought qdo had been updated to not require $QDO_DIR anymore.  `qdo.core.launch` has some logic to set `os.environ['QDO_DIR']` if it isn't already set, but this isn't a heavily used/tested feature.  I'm also a "add local check-out to my PYTHONPATH" kinda guy and have never personally used a real installation of qdo (while at the same time agreeing that if we provide a setup.py, it should work; providing a broken one is worse than not providing one at all).

for the record, here is the PR that re-organized the package and setup.py: https://bitbucket.org/berkeleylab/qdo/pull-requests/48/console-scripts-project-organization/diff

**Comment by weaverba137** [comment]
@sbailey, it sounds like there is no action to be taken here in desiconda itself. Can this be closed?
