### ISSUE TITLE
problem importing skimage with 20190311-1.2.7-img module

### ISSUE THREAD

**Issue by moustakas** [desihub/desiconda#31]
See below for the Traceback when importing `skimage` with `20190311-1.2.7-img`. There is no issue when using `20180512-1.2.5-img`.
```
ioannis@edison07:~% desiconda_version=20190311-1.2.7-img
ioannis@edison07:~% module use /global/common/software/desi/cori/desiconda/$desiconda_version/modulefiles
ioannis@edison07:~% module load desiconda
ioannis@edison07:~% 
ioannis@edison07:~% ipython
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import skimage                                                                                                   
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-aa248544dc2e> in <module>
----> 1 import skimage

/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/conda/lib/python3.6/site-packages/skimage/__init__.py in <module>
    165         _raise_build_error(e)
    166     # All skimage root imports go here
--> 167     from .util.dtype import (img_as_float32,
    168                              img_as_float64,
    169                              img_as_float,

/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/conda/lib/python3.6/site-packages/skimage/util/__init__.py in <module>
      6 from .apply_parallel import apply_parallel
      7 
----> 8 from .arraycrop import crop
      9 from ._regular_grid import regular_grid, regular_seeds
     10 from .unique import unique_rows

/global/common/software/desi/cori/desiconda/20190311-1.2.7-img/conda/lib/python3.6/site-packages/skimage/util/arraycrop.py in <module>
      6 
      7 import numpy as np
----> 8 from numpy.lib.arraypad import _validate_lengths
      9 
     10 

ImportError: cannot import name '_validate_lengths'
```

**Comment by sbailey** [comment]
This looks like a numpy version incompatibility.  desiconda 20190311 has numpy 1.16.2 and skimage 0.14.1, while 20180512 has numpy 1.13.3 an skimage 0.13.1.  Shame on skimage for importing a _-prefixed function.

From https://stackoverflow.com/questions/54241226/importerror-cannot-import-name-validate-lengths it appears that this was fixed in skimage 0.14.2.

Normally we would not post-facto update a desiconda installation, but we could consider updating skimage in this case if it doesn't bring in a bunch of other new updates too.

**Comment by moustakas** [comment]
If it's a quick fix, that'd be helpful.

**Comment by sbailey** [comment]
skimage does not appear to have been installed via conda (it doesn't appear in `conda list`) and I also don't see it in any of the desiconda rules files.  Does anyone know how it was installed in this desiconda version?  i.e. was it already installed by hand via pip?

**Comment by weaverba137** [comment]
Since this problem was observed on edison in a version from 2019 I'm closing this as no longer relevant. Feel free to reopen if that's not the case.
