### ISSUE TITLE
Add kapteyn package

### ISSUE THREAD

**Issue by tskisner** [desihub/desiconda#32]
This is needed by tilepicker.

**Comment by sbailey** [comment]
@srheft in the spirit of limiting our required dependencies, could the functionality of this be handled by astropy functions instead?  Specifically what features of kapteyn are needed?  It looks like it has some useful tools but only a small contributor base and isn't a broadly used community package, thus I'm hesitant to bring it on as a required dependency for the next 5+ years.

**Comment by Srheft** [comment]
we can check to see if wcs.Transformation in kapteyn can be replaced by one of the astropy.wcs projections.

**Comment by weaverba137** [comment]
Given the dates, I assume that the problem was indeed solved using astropy. Feel free to reopen if not.
