### ISSUE TITLE
Conda-installed ld incompatible with Cray system one

### ISSUE THREAD

**Issue by tskisner** [desihub/desiconda#36]
See discussion in https://github.com/desihub/fiberassign/issues/243

Upstream anaconda tracking this in:

https://github.com/ContinuumIO/anaconda-issues/issues/11152

I suggest we add a config option `CONDA_LD` which if set to `yes` will leave this alone and otherwise will move the conda-installed `ld` utility out of the way before proceeding.

**Comment by sbailey** [comment]
@tskisner could you review the upstream anaconda ticket (now closed) to see whether you expect that to fix our problem?  Was your workaround in desihub/fiberassign#243 a "by hand" patch that may need to be re-applied in a new desiconda release, or is the workaround in desiconda itself (in which case do you think it is still needed?)

**Comment by sbailey** [comment]
This worked fine with new desiconda installation 20200801-1.4.0-spec, so I'm closing this ticket.
