### ISSUE TITLE
pyfftw

### ISSUE THREAD

**Issue by ashleyjross** [desihub/desiconda#43]
pyfftw is required for the blinding (and then likely the BAO reconstruction) codes applied to LSS catalogs. If it could become part of the desi environment, that would be wonderful, but this is not urgent. (The pip install is easy and works for me currently, but since this will be part of official LSS catalogs for Y1, it would be good to have a stable desi version associated with that.)

**Comment by weaverba137** [comment]
@ashleyjross, is this still desired for Y1/DR1 work?  We could install it by hand in the existing, current desiconda.

**Comment by ashleyjross** [comment]
I think our work around was to use the cosmodesi environment for the blinding (via source /global/common/software/desi/users/adematti/cosmodesi_environment.sh main) and not just for this particular but for other coding issues that one might expect what is in cosmodesi to cover. I'm therefore closing the particular comment, but it is worth mentioning here that the combination of desihub and cosmodesi is used in many of the later stage LSS products. I will endeavor to document it all properly.
