### ISSUE TITLE
installation failure on perlmutter

### ISSUE THREAD

**Issue by marcelo-alvarez** [desihub/desiconda#44]
@sbailey tried installing the (still under development and being tested) [update](https://github.com/desihub/desiconda/tree/update) branch of desiconda on perlmutter and it didn't work out of the box, ending with:
```
  checking for MPI compile and link ...
  /opt/cray/pe/craype/2.7.12/bin/cc -shared -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /global/common/software/desi/users/sjbailey/perlmutter/desiconda/20211215-2.0.0/conda/include -fPIC -O2 -isystem /global/common/software/desi/users/sjbailey/perlmutter/desiconda/20211215-2.0.0/conda/include -O3 -fPIC -pthread -fPIC -I/global/common/software/desi/users/sjbailey/perlmutter/desiconda/20211215-2.0.0/conda/include/python3.9 -c _configtest.c -o _configtest.o
  nvc-Error-Unknown switch: -Wno-unused-result
  nvc-Error-Unknown switch: -fwrapv
  failure.
  removing: _configtest.c _configtest.o
  error: Cannot compile MPI programs. Check your configuration!!!
  ----------------------------------------
  ERROR: Failed building wheel for mpi4py
Failed to build mpi4py
ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects
ERROR installing pip packages; exiting
```
the full log is at /global/cfs/cdirs/desi/users/sjbailey/desiconda2/perlmutter-install.log  (accessible from perlmutter-p1.nersc.gov or dtn01.nersc.gov while cori is down).

**Comment by sbailey** [comment]
FWIW, instructions from NERSC about building mpi4py based on a conda environment created off of their conda installation:
https://docs.nersc.gov/development/languages/python/using-python-perlmutter/

```
module load PrgEnv-gnu cudatoolkit python
conda create -n cudaaware python=3.9 -y
source activate cudaaware
MPICC="cc -target-accel=nvidia80 -shared" pip install --force --no-cache-dir --no-binary=mpi4py mpi4py
```

**Comment by tskisner** [comment]
Also, if you wanted to compile mpi4py using the nvidia PrgEnv, then you can try:
```
MPICC=cc CC=nvc CFLAGS="-noswitcherror" pip install mpi4py
```

**Comment by marcelo-alvarez** [comment]
> Also, if you wanted to compile mpi4py using the nvidia PrgEnv, then you can try:
> 
> ```
> MPICC=cc CC=nvc CFLAGS="-noswitcherror" pip install mpi4py
> ```

Thanks, will keep this in mind.

**Comment by marcelo-alvarez** [comment]
I submitted #47 to fix this issue.
