### ISSUE TITLE
Decide on how speclite will be installed

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiconda#53]
Recent desiconda and pipeline software stacks have speclite installed in two different places.  For example in release 22.2, `conda list` reports that speclite 0.14 is installed, while module list shows speclite 0.15.  Presumably the `desiInstall`ed module is hiding the `conda` or `pip` installed version of speclite.

This strikes me as somewhat dangerous. If nothing else, when someone is creating a [custom environment](https://desi.lbl.gov/trac/wiki/Pipeline/GettingStarted/NERSC#CustomizingYourDESIPythonEnvironment), they may end up with a version of speclite that is not actually used by the current pipeline.

**Comment by sbailey** [comment]
Thanks for catching that.  We had intended to remove speclite from the desiconda installation and only use it as a versioned software module instead, but it looks like `conf/conda-pkgs.sh` still is installing speclite into the base desiconda environment.

I'm flagging this for the DR1 project to remind us to remove it from the next desiconda installation.  @marcelo-alvarez

**Comment by weaverba137** [comment]
@marcelo-alvarez, is there a particular reason you assigned me to a closed ticket?

**Comment by marcelo-alvarez** [comment]
@weaverba137 Thanks for inquiring about this. I (un)assigned multiple people to closed tickets yesterday as part of a misguided attempt at retroactive record keeping for tickets in the Perlmutter project. It won't happen again.
