### ISSUE TITLE
Extraneous script defined but not used.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiconda#55]
What is the purpose of [this line](https://github.com/desihub/desiconda/blob/67490c29d0b179b6cb14b72500b45db14107dad0/install.sh#L25)?  It is not used in `install.sh` itself, nor is it exported so that it can be used by other programs.

**Comment by marcelo-alvarez** [comment]
It is indeed extraneous, a remnant from an earlier version. Good catch. Feel free to remove the line. Thanks.
