### ISSUE TITLE
Environment variable to point to desiconda "aux" directory.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiconda#6]
Currently the environment variable `DESICONDA` points to the anaconda install directory, *e.g.*, `/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda`.  However, I can't find a similar variable that points to the equivalent `spectro_aux` directory.  This would be very useful for people needing to compile code against, say the cfitsio library.

**Comment by tskisner** [comment]
Ok, will add this when I'm updating things next, probably tomorrow.

**Comment by tskisner** [comment]
I added an environment variable, but note that this is hardly ever necessary.  The appropriate directories containing compiled code are already added to PATH, CPATH, LIBRARY_PATH, LD_LIBRARY_PATH, PYTHONPATH, and PKG_CONFIG_PATH.  So libraries and headers should be automatically found during compilation.

**Comment by tskisner** [comment]
Closed by b3a14c390f33dff299193755e40302ce6d544cbf
