### ISSUE TITLE
Install NOIRLab software

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiconda#69]
For DR1, especially *public* DR1, it would be useful to have some NOIRLab software installed in the DR1 desiconda package.  Specifically:

* `sparclclient`: client for retrieving full spectra.
* `astro-datalab`: client for querying Data Lab databases, etc.

These don't have an especially long list of requirements. In fact, in a recent test, I was able to `pip install --no-deps` for these packages and they worked fine in the `test-24.4` environment. In other words, most likely all the requirements are already included in desiconda.

**Comment by weaverba137** [comment]
*Caveat*: I've recently found that `astro-datalab` (and possibly `sparclclient` as well) have an unusually restrictive set of dependencies. For example, I was using a Python environment with Astropy 6 installed, and installing `astro-datalab` took that back to an Astropy 5 version.

**Comment by sbailey** [comment]
My initial reaction is that this is similar to tensorflow, pytorch, or jax — reasonable packages that someone might want to use for analysis, but that we shouldn't commit to installing in our core desiconda environment for productions.  I think it would be better to encourage user installations, user conda environments, or for NOIRLab to provide a container that could run anywhere including NERSC.

**Comment by weaverba137** [comment]
I agree, especially given my recent caveat above. I will close this. We can reopen if the situation changes.
