### ISSUE TITLE
bump galsim to `v1.4.4`

### ISSUE THREAD

**Issue by esheldon** [desihub/desiconda#8]
I think this might be the last in the 1.4 series, so is I think worth moving to.  @rmjarvis can hopefully comment

**Comment by rmjarvis** [comment]
1.5 should be out within the month.  1.4.4 is a [bug fix](https://github.com/GalSim-developers/GalSim/blob/releases/1.4/CHANGELOG.md#changes-from-v143-to-v144) release.

**Comment by esheldon** [comment]
I moved to docker, which I think solves all of my problems.  I will close this.
